services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - fullstack-network
    ports:
      - 5433:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    image: fullstack/backend
    build: ./back-end
    networks:
      - fullstack-network
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env

networks:
  fullstack-network:
    name: fullstack-network
    driver: bridge

volumes:
  postgres-volumes:
